#!/bin/sh

EXIT_CODE=0

COMMIT_MSG=$(git log -1 --pretty=%B)

if echo "$COMMIT_MSG" | grep -q "\[cr\]"; then
   echo "=====[ Running the post-commit script... ]====="
   coderabbit review --plain --type committed || EXIT_CODE=$?
else
   echo "=====[ Skipping the post-commit script... ]====="
fi

echo "The \`post-commit\` script has completed. Exiting with a code of ${EXIT_CODE}"
exit $EXIT_CODE
