#!/bin/sh

EXIT_CODE=0

# a.k.a. `type:check`
mypy. || EXIT_CODE=$?

# a.k.a. `test`
pytest || EXIT_CODE=$?

echo "The \`pre-push\` script has completed. Exiting with a code of ${EXIT_CODE}"
exit $EXIT_CODE
