#!/bin/sh

EXIT_CODE=0

# a.k.a. `type:check`
uv run mypy. || EXIT_CODE=$?

uv run pytest || EXIT_CODE=$?

echo "The \`pre-push\` script has completed. Exiting with a code of ${EXIT_CODE}"
exit $EXIT_CODE
